apiVersion: v2
appVersion: 5.0.2
dependencies:
- condition: zammadConfig.elasticsearch.enabled
  name: elasticsearch
  repository: https://helm.elastic.co
  version: 7.15.0
- condition: zammadConfig.memcached.enabled
  name: memcached
  repository: https://charts.bitnami.com/bitnami
  version: 5.15.5
- condition: zammadConfig.postgresql.enabled
  name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 10.12.4
- condition: zammadConfig.redis.enabled
  name: redis
  repository: https://charts.bitnami.com/bitnami
  version: 15.4.1
description: Zammad is a web based open source helpdesk/customer support system with
  many features to manage customer communication via several channels like telephone,
  facebook, twitter, chat and e-mails.
home: https://zammad.org
icon: https://raw.githubusercontent.com/zammad/zammad-documentation/master/images/zammad_logo_600x520.png
maintainers:
- email: monotek23@gmail.com
  name: monotek
- email: contact@zammad.com
  name: martini
name: zammad
sources:
- https://github.com/zammad/zammad
- https://github.com/zammad/zammad-docker-compose
- https://github.com/zammad/zammad-helm
version: 6.0.1
