apiVersion: v1
kind: PersistentVolume
metadata:
  name: zammad
  labels:
    type: local
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /root/data/zammad

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: zammad-master
  labels:
    type: local
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /root/data/zammad-master

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres
  labels:
    type: local
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /root/data/zammad-postgres

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis
  labels:
    type: local
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /root/data/zammad-redis
